version: '3.8'

networks:
  default:
    name: myongji-graduate

volumes:
  data:
    driver: local
  config:
    driver: local

services:
  db:
    image: mysql:8.0.29
    container_name: mg-mysql
    ports:
      - 33066:3306
    volumes:
      - data:/var/lib/mysql
      - config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: myongji_graduate
    platform: linux/x86_64
    restart: always
