FROM openjdk:11

ARG JAR_FILE=build/libs/*.jar
ARG PROFILE=prod
ARG DATASOURCE_URL
ARG DATASOURCE_USERNAME
ARG DATASOURCE_PASSWORD
ARG JWT_SECRET

COPY ${JAR_FILE} app.jar

ENV PROFILE=${PROFILE}
ENV DATASOURCE_URL=${DATASOURCE_URL}
ENV DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
ENV DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=${PROFILE}", "/app.jar"]
