package com.plzgraduate.myongjigraduatebe.core.exception;

public enum ErrorCode {

	INTERNAL_SEVER_ERROR,
	INVALIDATED_GRADUATION_CATEGORY,
	UNFITTED_GRADUATION_CATEGORY,
	UNREGISTERED_USER,
	INVALIDATED_STUDENT_NUMBER_TYPE,
	INVALIDATED_PASSWORD_TYPE,
	MISMATCHED_PASSWORD,
	NOT_FOUND_AUTHID,
	INVALIDATED_AUTHID_TYPE,
	INCORRECT_PASSWORD,
	DUPLICATED_STUDENT_NUMBER,
	DUPLICATED_AUTHID,
	NOT_FOUND_STUDENT_NUMBER,
	INVALIDATED_AUTH_TOKEN,
	INCORRECT_STUDENT_NUMBER,
	NON_EXISTED_LECTURE,
	UNSUPPORTED_STUDENT_CATEGORY,

}
