package com.plzgraduate.myongjigraduatebe.graduation.application.usecase;

import com.plzgraduate.myongjigraduatebe.graduation.domain.model.DetailGraduationResult;

public interface CalculateDualElectiveMajorDetailGraduationUseCase extends CalculateDetailGraduationUseCase {

	DetailGraduationResult isolateDualElectiveMajorDetailGraduation(
		DetailGraduationResult dualMajorDetailGraduationResult);
}
