package com.plzgraduate.myongjigraduatebe.graduation.application.usecase;

public interface CalculatePrimaryBasicAcademicalCultureDetailGraduationUseCase
	extends CalculateDetailGraduationUseCase {
}
