ALTER TABLE fusion_major_policy
    ADD COLUMN business_required_credit INT NULL AFTER required_credit,
    ADD COLUMN basic_credit INT NOT NULL DEFAULT 0 AFTER business_required_credit,
    ADD COLUMN business_basic_credit INT NULL AFTER basic_credit,
    ADD COLUMN primary_major_credit INT NOT NULL DEFAULT 36 AFTER business_basic_credit,
    ADD COLUMN business_primary_major_credit INT NULL AFTER primary_major_credit;

ALTER TABLE fusion_major_lecture
    ADD COLUMN requirement_area VARCHAR(30) NOT NULL DEFAULT 'MAJOR' AFTER equivalence_key,
    ADD COLUMN mandatory TINYINT NOT NULL DEFAULT 0 AFTER requirement_area,
    ADD INDEX idx_fusion_major_lecture_area (policy_id, requirement_area, mandatory);

UPDATE fusion_major_policy
SET basic_credit = CASE
    WHEN fusion_major = '응용데이터사이언스' THEN 3
    WHEN fusion_major = '인문ICT콘텐츠' THEN 9
END
WHERE fusion_major IN ('응용데이터사이언스', '인문ICT콘텐츠');

INSERT INTO fusion_major_policy
    (fusion_major, required_credit, business_required_credit,
     basic_credit, business_basic_credit,
     primary_major_credit, business_primary_major_credit,
     start_entry_year, end_entry_year)
VALUES
    ('휴먼복지행정', 36, NULL, 18, NULL, 36, NULL, 16, 99),
    ('Entrepreneurship', 45, 36, 6, 0, 36, 45, 16, 99),
    ('AI엔터프라이즈솔루션', 45, 36, 3, 0, 36, 45, 16, 99),
    ('사회혁신', 36, NULL, 6, NULL, 36, NULL, 16, 99),
    ('글로벌스터디스', 36, NULL, 0, NULL, 36, NULL, 16, 99),
    ('법조공직인재', 36, NULL, 3, NULL, 36, NULL, 16, 99),
    ('코칭상담심리', 36, NULL, 3, NULL, 36, NULL, 16, 99);

INSERT INTO fusion_major_lecture
    (policy_id, lecture_id, equivalence_key, requirement_area, mandatory)
SELECT p.id, mapping.lecture_id, mapping.equivalence_key, mapping.area, mapping.mandatory
FROM fusion_major_policy p
JOIN (
    -- 응용데이터사이언스: AI·SW대학 개설교양 중 3학점
    SELECT '응용데이터사이언스' fusion_major, 'KMD02194' lecture_id, 'AI_SW_BUSINESS' equivalence_key, 'BASIC' area, 0 mandatory
    UNION ALL SELECT '응용데이터사이언스','KMF02113','FUSION_ENGINEERING_DESIGN','BASIC',0
    UNION ALL SELECT '응용데이터사이언스','KMD02135','COPYRIGHT_SOFTWARE','BASIC',0
    UNION ALL SELECT '응용데이터사이언스','KMI02112','COMPUTER_LOGIC','BASIC',0
    UNION ALL SELECT '응용데이터사이언스','KMC02113','DESIGN_INTRO','BASIC',0
    UNION ALL SELECT '응용데이터사이언스','KMD02193','MARKETING_AI_SW','BASIC',0
    UNION ALL SELECT '응용데이터사이언스','KMF02112','STARTUP_MANAGEMENT','BASIC',0
    UNION ALL SELECT '응용데이터사이언스','KME02106','STATISTICS_INTRO','BASIC',0
    UNION ALL SELECT '응용데이터사이언스','KME02107','LINEAR_ALGEBRA','BASIC',0

    -- 인문ICT콘텐츠: 인문콘텐츠의이해 필수 + 선택 2과목
    UNION ALL SELECT '인문ICT콘텐츠','KMB02141','HUMANITIES_CONTENTS_INTRO','BASIC',1
    UNION ALL SELECT '인문ICT콘텐츠','KMB02142','HUMANITIES_DATA','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02128','INFORMATION_LITERACY','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02122','WHAT_IS_HISTORY','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02125','CREATIVE_IMAGINATION','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02123','PHILOSOPHY_WALK','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02127','KOREAN_CULTURE_WRITING','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02120','ARAB_LANGUAGE_CULTURE','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02121','CHINESE_LANGUAGE_CULTURE','BASIC',0
    UNION ALL SELECT '인문ICT콘텐츠','KMB02124','JAPANESE_LANGUAGE_CULTURE','BASIC',0

    -- 휴먼복지행정
    UNION ALL SELECT '휴먼복지행정', 'HBA01271', 'SOCIAL_WELFARE_INTRO', 'MAJOR', 1
    UNION ALL SELECT '휴먼복지행정','HBA01574','SOCIAL_WELFARE_POLICY','MAJOR',1
    UNION ALL SELECT '휴먼복지행정','HBA01623','SOCIAL_WELFARE_LAW','MAJOR',1
    UNION ALL SELECT '휴먼복지행정','HBA01614','SOCIAL_WELFARE_RESEARCH','MAJOR',1
    UNION ALL SELECT '휴먼복지행정','HBA01471','SOCIAL_WELFARE_ADMIN','MAJOR',1
    UNION ALL SELECT '휴먼복지행정','HBA01408','SOCIAL_WELFARE_PRACTICUM','MAJOR',1
    UNION ALL SELECT '휴먼복지행정','HAK01496','HUMAN_BEHAVIOR_ENV','MAJOR',1
    UNION ALL SELECT '휴먼복지행정','HBA01223','VOLUNTEERISM','MAJOR',0
    UNION ALL SELECT '휴먼복지행정','HAK01495','CHILD_WELFARE','MAJOR',0
    UNION ALL SELECT '휴먼복지행정','HAK01389','MENTAL_HEALTH','MAJOR',0
    UNION ALL SELECT '휴먼복지행정','HAK01464','FAMILY_WELFARE','MAJOR',0
    UNION ALL SELECT '휴먼복지행정','HAK01352','PROGRAM_DEVELOPMENT_EVAL','MAJOR',0
    UNION ALL SELECT '휴먼복지행정','HAH01472','YOUTH_WELFARE','MAJOR',0
    UNION ALL SELECT '휴먼복지행정','KMD02118','COMMUNITY_WELFARE','BASIC',1
    UNION ALL SELECT '휴먼복지행정','KMD02119','SOCIAL_WORK_PRACTICE','BASIC',1
    UNION ALL SELECT '휴먼복지행정','KMM02124','WELFARE_ETHICS','BASIC',0
    UNION ALL SELECT '휴먼복지행정','KMM02122','DISABILITY_WELFARE','BASIC',0
    UNION ALL SELECT '휴먼복지행정','KMM02121','ELDERLY_WELFARE','BASIC',0

    -- Entrepreneurship
    UNION ALL SELECT 'Entrepreneurship','HBX01123','ENTREPRENEURSHIP','MAJOR',1
    UNION ALL SELECT 'Entrepreneurship','HBX01137','BUSINESS_MODEL','MAJOR',1
    UNION ALL SELECT 'Entrepreneurship','HBX01117','CSR','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01136','INTERNSHIP','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01104','ACCOUNTING_PRINCIPLES','MAJOR',1
    UNION ALL SELECT 'Entrepreneurship','HBX01140','BUSINESS_STRATEGY','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01134','ORGANIZATIONAL_BEHAVIOR','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01126','SCM','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01138','CORPORATE_FINANCE','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01132','CONSUMER_BEHAVIOR','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01139','MARKETING_RESEARCH','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01131','SERVICE_OPERATIONS','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01106','MARKETING','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01143','OPERATIONS','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01127','INTERNATIONAL_BUSINESS','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01125','BUSINESS_INFORMATION','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','HBX01135','COMPUTER_PROGRAMMING','MAJOR',0
    UNION ALL SELECT 'Entrepreneurship','KMD02107','BUSINESS_STATISTICS','BASIC',1
    UNION ALL SELECT 'Entrepreneurship','KMD02114','MICROECONOMICS','BASIC',1

    -- AI엔터프라이즈솔루션(구 프로세스자동화경영)
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03385','RPA','MAJOR',1
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03386','RPA_PRACTICE','MAJOR',1
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03512','INTELLIGENT_AUTOMATION','MAJOR',1
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HBX01124','PROGRAMMING_BASICS','MAJOR',1
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HBX01125','BUSINESS_INFORMATION','MAJOR',1
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HBX01104','ACCOUNTING_PRINCIPLES','MAJOR',1
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HBX01146','ERP_INTRO','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HBX01122','BUSINESS_PROCESS_ANALYTICS','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03383','MACHINE_LEARNING','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HBX01141','DATABASE_ANALYSIS','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03503','DATA_SCIENCE_PROGRAMMING','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HED00201','FUSION_R_STATISTICS','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HED00207','FUSION_R_STATISTICS','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HED00205','FUSION_DATABASE','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HED01208','FUSION_DATABASE','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HEB01203','BASIC_WEB_PROGRAMMING','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HEB01303','MOBILE_PROGRAMMING','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03464','ACCOUNTING_INFORMATION','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03463','ERP_SCM','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03387','ERP_PROGRAMMING','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03384','OBJECT_ORIENTED_LANGUAGE','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HEC01202','PATTERN_PROGRAMMING','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03388','ERP_DATA_ANALYTICS','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03389','PYTHON_APPLICATION','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','HCB03267','DATA_ANALYSIS_PROGRAMMING','MAJOR',0
    UNION ALL SELECT 'AI엔터프라이즈솔루션','KMD02107','BUSINESS_STATISTICS','BASIC',1

    -- 글로벌스터디스
    UNION ALL SELECT '글로벌스터디스','HYB01201','GLOBAL_STUDIES_INTRO','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBA01430','URBAN_ADMIN','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBA01472','PUBLIC_FINANCE','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBB01262','FOREIGN_POLICY','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBA01309','ENV_POLICY','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBA01110','LEADERSHIP_ORG_ENG','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBB01213','INTERNATIONAL_ORG','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBA01113','NONPROFIT_ENG','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBB01361','INTL_POLITICS_PRACTICE','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBB01379','INTL_POLITICS_DEBATE','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBB01240','INTL_POLITICAL_ECONOMY','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBB01270','INTL_POLITICS_JUSTICE','MAJOR',0
    UNION ALL SELECT '글로벌스터디스','HBB01319','INTL_SECURITY','MAJOR',0

    -- 법조공직인재
    UNION ALL SELECT '법조공직인재','HDA01127','LEGAL_LOGIC_1','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01128','LEGAL_LOGIC_2','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01508','LEGAL_HISTORY_1','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01509','LEGAL_HISTORY_2','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01462','LEGAL_PHILOSOPHY','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01201','CONSTITUTION_1','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01202','CONSTITUTION_2','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01230','ADMIN_LAW_1','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01331','ADMIN_LAW_2','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01110','CRIMINAL_GENERAL_1','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01210','CRIMINAL_GENERAL_2','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01211','CRIMINAL_SPECIFIC','MAJOR',0
    UNION ALL SELECT '법조공직인재','HDA01312','CRIMINAL_PROCEDURE','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBA01211','PERSONNEL_ADMIN','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBA01210','ADMIN_ORGANIZATION','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBA01221','POLICY_INTRO','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBA01624','GOVERNMENT_BUDGET','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBE01102','MARKET_FIRM','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBE01318','PUBLIC_FINANCE_ECON','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBE01237','TAX_ACCOUNTING','MAJOR',0
    UNION ALL SELECT '법조공직인재','HBE01103','NATIONAL_ECONOMY','MAJOR',0

    -- 코칭상담심리
    UNION ALL SELECT '코칭상담심리','HAH01316','COUNSELING_THEORY','MAJOR',1
    UNION ALL SELECT '코칭상담심리','HAH01317','PSYCHOLOGICAL_TEST','MAJOR',1
    UNION ALL SELECT '코칭상담심리','HAH01319','FAMILY_COUNSELING','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HAH01237','HUMAN_RELATIONS','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HAH01372','CAREER_COUNSELING','MAJOR',1
    UNION ALL SELECT '코칭상담심리','HAH01373','PERSONALITY_PSYCHOLOGY','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HAH01403','GROUP_COUNSELING','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HAH01381','HRD','MAJOR',1
    UNION ALL SELECT '코칭상담심리','HAH01236','EDUCATION_ADMIN','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HBA01211','PERSONNEL_ADMIN','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HBA01310','ORGANIZATION_BEHAVIOR','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HBA01110','LEADERSHIP_ORG_ENG','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HBA01214','CIVIL_SOCIETY_ADMIN','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HBA01472','PUBLIC_FINANCE','MAJOR',0
    UNION ALL SELECT '코칭상담심리','HBA01312','ADMIN_MANAGEMENT','MAJOR',0

    -- 사회혁신 전용 필수. 나머지 24학점은 참여학과 전공 인정 규칙으로 보강한다.
    UNION ALL SELECT '사회혁신','HGA01101','SOCIAL_INNOVATION_FOUNDATION','MAJOR',1
    UNION ALL SELECT '사회혁신','HGA01102','SOCIAL_PROBLEM_DISCOVERY','MAJOR',1
    UNION ALL SELECT '사회혁신','HGA01103','SOCIAL_PROBLEM_PROTOTYPE','MAJOR',1
    UNION ALL SELECT '사회혁신','HGA01104','SOCIAL_PROBLEM_PRACTICE','MAJOR',1
) mapping ON mapping.fusion_major = p.fusion_major
JOIN lecture l ON l.id = mapping.lecture_id
WHERE NOT EXISTS (
    SELECT 1
    FROM fusion_major_lecture existing
    WHERE existing.policy_id = p.id
      AND existing.lecture_id = mapping.lecture_id
);
