name: PR Label Automation
on:
  schedule:
    - cron: '0 0 * * *'  # Executes daily at midnight

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Update PR Labels
        uses: actions/github-script@v5
        with:
          script: |
            const repo = context.repo;

            // Fetch all open PRs
            const prs = await github.rest.pulls.list({
              owner: repo.owner,
              repo: repo.repo,
              state: 'open',
            });

            for (const pr of prs.data) {
              const prNumber = pr.number;
              let labels = pr.labels.map(label => label.name);

              // Function to update label
              async function updateLabel(oldLabel, newLabel) {
                if (oldLabel) {
                  await github.rest.issues.removeLabel({
                    owner: repo.owner,
                    repo: repo.repo,
                    issue_number: prNumber,
                    name: oldLabel,
                  });
                }
                await github.rest.issues.addLabels({
                  owner: repo.owner,
                  repo: repo.repo,
                  issue_number: prNumber,
                  labels: [newLabel],
                });
              }

              // Check and update 'D-x' labels
              let dLabel = labels.find(label => label.startsWith("D-"));
              if (dLabel) {
                let day = parseInt(dLabel.split("-")[1]);
                if (day > 0) {
                  await updateLabel(dLabel, `D-${day - 1}`);
                  console.log(`Updated label from ${dLabel} to D-${day - 1} on PR #${prNumber}`);
                } else if (day === 0) {
                  // Handle 'D-0' logic here
                }
              } else {
                // Add 'D-5' label if no 'D-' label is present
                await updateLabel(null, 'D-5');
                console.log(`Added D-5 label to PR #${prNumber}`);
              }
            }
