name: PR Label Automation
on:
  schedule:
    - cron: '0 0 * * *'  # Executes daily at midnight

jobs:
  update-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check and Update PR Labels
        uses: actions/github-script@v5
        with:
          script: |
            const repo = context.repo;

            // Fetch all open PRs
            const prs = await github.rest.pulls.list({
              owner: repo.owner,
              repo: repo.repo,
              state: 'open',
            });

            for (const pr of prs.data) {
              const prNumber = pr.number;
              let labels = pr.labels.map(label => label.name);
              const hasDLabel = labels.some(label => label.startsWith("D-"));

              // Add 'D-5' label if no 'D-' label is present
              if (!hasDLabel) {
                await github.rest.issues.addLabels({
                  owner: repo.owner,
                  repo: repo.repo,
                  issue_number: prNumber,
                  labels: ['D-5'],
                });
                console.log(`Added D-5 label to PR #${prNumber}`);
              }

              // Update 'D-x' labels
              for (let label of labels) {
                if (label.startsWith("D-") && label !== "D-0") {
                  let day = parseInt(label.split("-")[1]);
                  if (day > 0) {
                    let newLabel = `D-${day - 1}`;
                    // Remove old label
                    await github.rest.issues.removeLabel({
                      owner: repo.owner,
                      repo: repo.repo,
                      issue_number: prNumber,
                      name: label,
                    });
                    // Add new label
                    await github.rest.issues.addLabels({
                      owner: repo.owner,
                      repo: repo.repo,
                      issue_number: prNumber,
                      labels: [newLabel],
                    });
                    console.log(`Updated label from ${label} to ${newLabel} on PR #${prNumber}`);
                  }

                  if (day === 1) {
                    // Handle 'D-0' logic here
                  }
                  break;
                }
              }
            }
